services:
  manager:
    build: CrackHashManager
    container_name: crackhash-manager
    ports:
      - "8080:8080"
    networks:
      - crackhash-net
    env_file:
      - .env
    environment:
      - WORKER_COUNT=${WORKER_COUNT:-1}

  worker:
    build: CrackHashWorker
    networks:
      - crackhash-net
    env_file:
      - .env
    deploy:
      replicas: ${WORKER_COUNT:-1}
    ports:
      - 8081

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - crackhash-net

networks:
  crackhash-net:
    driver: bridge